name: "Add a project to Taiko's ecosystem 🌐"
description: "Add a project to Taiko's ecosystem"
title: "Add [PROJECT_NAME] to the ecosystem page"
labels: ["area.website", "category.ecosystem"]
body:
  - type: markdown
    attributes:
      value: |
        This is an application to submit your project to be shown on the [Taiko ecosystem page](https://taiko.xyz/ecosystem).
        Please only submit a project if you are part of the team. DO NOT submit an application on behalf of a project if you don't work with them.
        If your project is already on the portal and you would like to update its information, please reach out to the team.
        **Please keep in mind: A submission doesn't guarantee a listing on the page.**

  - type: input
    id: project_name
    attributes:
      label: What is the name of your project?
    validations:
      required: true

  - type: input
    id: your_name
    attributes:
      label: What's your name?
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
    validations:
      required: true

  - type: input
    id: telegram
    attributes:
      label: Telegram
    validations:
      required: true

  - type: input
    id: project_link
    attributes:
      label: Please provide a link to your website, documentation, or project overview
    validations:
      required: true

  - type: input
    id: x_handle
    attributes:
      label: What is your project's X handle?
    validations:
      required: true

  - type: dropdown
    id: project_category
    attributes:
      label: Project Category
      options:
        - "Community"
        - "DeFi"
        - "Explorers"
        - "Gaming"
        - "Infrastructure"
        - "NFT"
        - "Privacy"
        - "Tooling"
        - "Wallet"
    validations:
      required: true

  - type: dropdown
    id: is_live
    attributes:
      label: Is your project currently live on Taiko mainnet?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: github_link
    attributes:
      label: Github Link of your project
    validations:
      required: true

  - type: textarea
    id: project_description
    attributes:
      label: Please provide a clear and comprehensive description of your project and what value it will bring to Taiko's ecosystem
    validations:
      required: true

  - type: input
    id: other_networks
    attributes:
      label: List of other networks you are deployed on
    validations:
      required: true

  - type: input
    id: verified_contract
    attributes:
      label: Link to verified contract on Taikoscan
      description: "For DeFi projects, this is a must question."
    validations:
      required: false

  - type: textarea
    id: logo
    attributes:
      label: Please share your logo
      description: 512x512 or 1:1 ratio is preferred. If no image is provided we will use a placeholder image.
    validations:
      required: false

  - type: input
    id: team_twitter_handle
    attributes:
      label: Please share the twitter handle of your team member who will be participating in our twitter activities.
    validations:
      required: false
